version: "2"
run:
  concurrency: 4
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - godox
    - gomoddirectives
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - paralleltest
    - tagliatelle
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    gocyclo:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
