run:
  concurrency: 4
  deadline: 5m

linters-settings:
  cyclop:
    max-complexity: 20
  gocyclo:
    min-complexity: 20

linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustruct
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - interfacer
    - maligned
    - gomnd
    - nestif
    - paralleltest
    - scopelint
    - testpackage
    - tparallel
    - wrapcheck
    - wsl
    - godox
    - forcetypeassert
    - nlreturn
    - tagliatelle
    - varnamelen
    - ireturn
    - varcheck
    - deadcode
    - golint
    - ifshort
    - structcheck
    - nosnakecase
    - lll
