// Code generated by "stringer -type=EventType -output=event_string.go"; DO NOT EDIT.

package sdkclient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllocateEventType-0]
	_ = x[DeallocateEventType-1]
}

const _EventType_name = "AllocateEventTypeDeallocateEventType"

var _EventType_index = [...]uint8{0, 17, 36}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
