name: Build Linux Binary
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build with Go
        run: cd simple-game-server-go/ && go build -v -o simple-game-server-linux
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: simple-game-server-linux
          path: simple-game-server-go/simple-game-server-linux
          retention-days: 5