name: build-and-release
on:
  pull_request:
  push:
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: 'go test -timeout=5m -race -v ./...'
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
