name: simple-game-server-go
on:
  pull_request:
  push:
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './simple-game-server-go'
    env:
      GOPRIVATE: ""
      GONOSUMDB: "github.com/Unity-Technologies/*"
      GOPROXY: https://github:${{ secrets.GITHUB_TOKEN }}@athens.prd.cds.internal.unity3d.com/
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          working-directory: './simple-game-server-go'
          skip-cache: true
          args: -v
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
          workdir: './simple-game-server-go'
      - name: Test
        run: 'go test -timeout=5m -race -v ./...'
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '-simple-game-server-go') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: './simple-game-server-go'
